update our .jenkins folder

diff --git a/.jenkins/run-tests b/.jenkins/run-tests
--- a/.jenkins/run-tests
+++ b/.jenkins/run-tests
@@ -4,105 +4,58 @@ if [[ -z $ELASTICSEARCH_VERSION ]]; then
   echo -e "\033[31;1mERROR:\033[0m Required environment variable [ELASTICSEARCH_VERSION] not set\033[0m"
   exit 1
 fi
-
 set -euxo pipefail
 
 TEST_SUITE=${TEST_SUITE-oss}
+DOTNET_VERSION=${TEST_SUITE-3.0.100}
+NODE_NAME=es1
+
+repo=$(pwd)
 elasticsearch_image=elasticsearch
-elasticsearch_url=https://elastic:changeme@localhost:9200
+elasticsearch_url=https://elastic:changeme@${NODE_NAME}:9200
 if [[ $TEST_SUITE != "xpack" ]]; then
   elasticsearch_image=elasticsearch-${TEST_SUITE}
-  elasticsearch_url=http://localhost:9200
+  elasticsearch_url=http://${NODE_NAME}:9200
 fi
+
+function cleanup {
+  status=$?
+  set +x
+  ELASTICSEARCH_VERSION=${elasticsearch_image}:${ELASTICSEARCH_VERSION} \
+    NODE_NAME=${NODE_NAME} \
+    NETWORK_NAME=elasticsearch \
+    CLEANUP=true \
+    bash ./.jenkins/run-elasticsearch.sh
+  # Report status and exit
+  if [[ "$status" == "0" ]]; then
+    echo -e "\n\033[32;1mSUCCESS run-tests\033[0m"
+    exit 0
+  else
+    echo -e "\n\033[31;1mFAILURE during run-tests\033[0m"
+    exit ${status}
+  fi
+}
+trap cleanup EXIT
 
 echo -e "\033[1m>>>>> Start [$ELASTICSEARCH_VERSION container] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m"
 
-ELASTICSEARCH_VERSION=$(elasticsearch_image):$(ELASTICSEARCH_VERSION)
-NETWORK_NAME=elasticsearch
-bash ./run-elasticsearch.sh
+ELASTICSEARCH_VERSION=${elasticsearch_image}:${ELASTICSEARCH_VERSION} \
+  NODE_NAME=${NODE_NAME} \
+  NETWORK_NAME=elasticsearch \
+  DETACH=true \
+  bash ./.jenkins/run-elasticsearch.sh
 
-echo -e "\033[1m>>>>> Start [dotnet $DOTNET_VERSION container] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m"
-
-docker run --rm "mcr.microsoft.com/dotnet/core/sdk:DOTNET_VERSION"
+echo -e "\033[1m>>>>> Build [elastic/elasticsearch-net container] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m"
 
 docker build --file .jenkins/DockerFile --tag elastic/elasticsearch-net .
 
+echo -e "\033[1m>>>>> Run [elastic/elasticsearch-net container] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m"
 
-function cleanup {
-  docker container rm --force --volumes es1 > /dev/null 2>&1 || true
-  docker container rm --force --volumes elasticsearch-source > /dev/null 2>&1 || true
-  docker container rm --force --volumes go-elasticsearch > /dev/null 2>&1 || true
-}
-
-trap cleanup EXIT
-
-TIMEFORMAT="(Duration: %0lR)"
-
-echo -e "\033[1m>>>>> SETUP [$TEST_SUITE] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m"
-
-# Build the go-elasticsearch image
-docker build --file Dockerfile --tag elastic/go-elasticsearch .
-
-# Launch a single Elasticsearch node
-(make cluster detached=true version=$elasticsearch_image)
-
-# Store the Elasticsearch version and build hash
-ELASTICSEARCH_VERSION=$(docker run --network elasticsearch --rm appropriate/curl -sSk $elasticsearch_url | docker run -i --rm stedolan/jq -r '.version.number')
-ELASTICSEARCH_BUILD_HASH=$(docker run --network elasticsearch --rm appropriate/curl -sSk $elasticsearch_url | docker run -i --rm stedolan/jq -r '.version.build_hash')
-
-# Download Elasticsearch source code at ELASTICSEARCH_BUILD_HASH and store it in a container
-echo -e ">>>>> Downloading Elasticsearch repository @ $ELASTICSEARCH_BUILD_HASH..."
-time docker run --rm appropriate/curl --retry 3 -sSL "https://github.com/elastic/elasticsearch/archive/$ELASTICSEARCH_BUILD_HASH.zip" > "/tmp/elasticsearch-$ELASTICSEARCH_BUILD_HASH.zip"
-echo -e ">>>>> Extracting and storing to [elasticsearch-source] container..."
-time docker run --volume=/tmp:/tmp --workdir=/tmp --rm elastic/go-elasticsearch unzip -q -o "elasticsearch-$ELASTICSEARCH_BUILD_HASH.zip" '*.properties' '*.json' '*.y*ml'
-docker run --volume=/tmp:/tmp --workdir=/tmp --rm elastic/go-elasticsearch /bin/sh -c "
-  rm -rf /tmp/elasticsearch-$ELASTICSEARCH_BUILD_HASH.zip
-  rm -rf /tmp/elasticsearch/
-  mv /tmp/elasticsearch-$ELASTICSEARCH_BUILD_HASH* /tmp/elasticsearch/
-"
-docker create --name elasticsearch-source --volume /elasticsearch-source --name elasticsearch-source alpine /bin/true
-docker cp /tmp/elasticsearch elasticsearch-source:/elasticsearch-source
-
-# Launch the container; actual commands are called with "docker exec"
 docker run \
-  --name go-elasticsearch \
-  --network elasticsearch \
-  --env "ELASTICSEARCH_URL=$elasticsearch_url" \
-  --env "ELASTICSEARCH_VERSION=$ELASTICSEARCH_VERSION" \
-  --env "ELASTICSEARCH_BUILD_HASH=$ELASTICSEARCH_BUILD_HASH" \
-  --env "WORKSPACE=${WORKSPACE:-/workspace}" \
-  --volume "/go-elasticsearch" \
-  --volume "${WORKSPACE:-workspace}:${WORKSPACE:-/workspace}" \
-  --volumes-from "elasticsearch-source" \
+  --network=elasticsearch \
+  --env "DOTNET_VERSION" \
+  --name test-runner \
+  --volume ${repo}:/sln \
   --rm \
-  --detach \
-  elastic/go-elasticsearch sleep 3600
-
-# Run the tests
-# NOTE: Conditions needed to prevent early exit due to the 'set -e' option
-status=100
-case $TEST_SUITE in
-  "core" )
-    if bash .jenkins/tests-core.sh; then
-      status=$?
-    else
-      status=$?
-    fi
-    ;;
-  "xpack" )
-    if bash .jenkins/tests-xpack.sh; then
-      status=$?
-    else
-      status=$?
-    fi
-    ;;
-esac
-
-# Report status and exit
-if [[ $status == "0" ]]; then
-  echo -e "\n\033[32;1mSUCCESS\033[0m"
-  exit 0
-else
-  echo -e "\n\033[31;1mFAILURE\033[0m"
-  exit $status
-fi
+  elastic/elasticsearch-net \
+  ./build.sh rest-spec-tests -f create -e ${elasticsearch_url} -o /sln/build/output/rest-spec-junit.xml
